#!/usr/bin/php
<?php

// This script gives you a bunch of files to start with.
// Run this file with './INSTALL /path/to/installation'

require_once('installer/installer.php');

core_install();
user_install();