# ---------------------------------------------------------------- #
#   MASTER values are merged with the page-specific values         #
# ---------------------------------------------------------------- #

site_title: Phooey PHP Site Framework

css:
  - undohtml
  - global

ie_css:
  ie6: lte IE 6

jsapi: 
  library: jquery
  version: 1.2

js:
  - global

meta:
  description: Phooey is a tiny little framework to make building mostly-static web sites easy.
  keywords: php, framework, templating
  author: Jason T Johnson — postpostmodern.com
  copyright: (c) Copyright 2008 Jason T Johnson
