# ---------------------------------------------------------------- #
#   MASTER values are merged with the page-specific values         #
# ---------------------------------------------------------------- #

site_title: New Phooey Site

css:
  - reset
  - global

ie_css:
  ie6: lte IE 6

jsapi: 
  library: jquery
  version: 1.2

js:
  - global

meta:
  description: 
  keywords: 
  author: 
  copyright: 
  
content_filter: markdown
