# ---------------------------------------------------------------- #
#   Each PAGE of the site gets described here.                     #
# ---------------------------------------------------------------- #

home:
  title: Home

contact:
  title: Contact Us
  action: process_contact_form
  css:
    - contact
  vars:
    to: 
      - Some One <someone@example.com>
  