# ---------------------------------------------------------------- #
#   Each PAGE of the site gets described here.                     #
# ---------------------------------------------------------------- #

home:
  title: Home

contact:
  vars:
    to: someone@example.com
  title: Contact Us
  action: process_contact_form
  