# ---------------------------------------------------------------- #
#   MASTER values are merged with the page-specific values         #
# ---------------------------------------------------------------- #

site_title: New Phooey Site

doctype: XHTML 1.0 Strict

language: en-us

css:
  - reset
  - global

ie_css:
  ie6: lte IE 6

jsapi: 
  - [ jquery, 1.2 ]

js:
  - global

meta:
  description: Phooey is a simple framework for mostly-static sites.
  keywords: "PHP, framework, Phooey"
  author: Jason T Johnson (postpostmodern.com)
  copyright: (c) 2009 Jason T Johnson
  
content_filter: 
  - markdown
  - smartypants

