# ---------------------------------------------------------------- #
#   MASTER values are merged with the page-specific values         #
# ---------------------------------------------------------------- #

site_title: New Phooey Site

doctype: HTML 5

language: en-us

favicon: true

allowed_methods: 
  - GET

css:
  - [ all.css, all ]

ie_css:
  ie6: lte IE 6

jsapi: 
  - [ jquery, 1.4 ]

js:
  - global.js

meta:
  description: Phooey is a simple framework for mostly-static sites.
  keywords: "PHP, framework, Phooey"
  author: Jason T Johnson (postpostmodern.com)
  copyright: (c) 2009 Jason T Johnson
  
content_filter: 
  - markdown
  - smartypants

