---
home: 
  title: Home
contact: 
  title: Contact Us
  actions: 
    - 
      - GET
      - process_contact_form
    - 
      - POST
      - process_contact_form
  css: 
    - contact
  vars: 
    to: 
      - Some One <someone@example.com>
guide: 
  title: Markup Guide
