# ---------------------------------------------------------------- #
#   Each TEMPLATE is a list of PARTS.                              #
#   PARTS are found in the templates directory.                    #
# ---------------------------------------------------------------- #

default:
  - open
  - header
  - CONTENT
  - footer
  - close